.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH show 1  "show " 
.SH NAME
show \- Display metadata about a crate.
.SH SYNOPSIS
\fBshow\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIname\fR] 
.SH DESCRIPTION
Display metadata about a crate.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
[\fIname\fR]
The name of the crate to show.
.SH EXTRA
Thank you for using crates_cli!
.SH AUTHORS
Will Hopkins <willothyh@gmail.com>
