.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH crate 1  "crate 0.1.0" 
.SH NAME
crate
.SH SYNOPSIS
\fBcrate\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
crate\-find(1)
Search for crates on crates.io.
.TP
crate\-show(1)
Display metadata about a crate.
.TP
crate\-help(1)
Print this message or the help of the given subcommand(s)
.SH EXTRA
.SH VERSION
v0.1.0
.SH AUTHORS
Will Hopkins <willothyh@gmail.com>
