[package]
name = "crates_cli"
version = "0.1.0"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com>"]
description = "A command line interface for finding and managing crates."

[dependencies]
clap = { version = "3.1.18", features = ["cargo", "wrap_help", "env"] }
crates_io_api = "0.8.0"
spinners = "4.0.0"
termion = "1.5.6"
