[package]
name = "crates_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.18"
crates_io_api = "0.8.0"
spinners = "4.0.0"
termion = "1.5.6"
